### PR TITLE
Update to WP 4.8.1 

### PR DESCRIPTION
**Pull request by jtsternberg**
Mostly an update, but also added hook completions for things like `aa_init` and `af_the_content`, which will autocomplete with the following:
```
add_action( 'init', ${2:'${1:callback}'}${3} );
```
```
add_filter( 'the_content', ${2:'${1:callback}'}${3} );
```

### CODE REVIEW

**Comment by purplefish32** [comment]
Is this mergable ?

**Comment by jtsternberg** [comment]
Yes it should merge just fine.

**Comment by jtsternberg** [comment]
Let me know if you want me to merge, and I can work on getting it tagged so it shows as an update in Package Control.

**Comment by purplefish32** [comment]
Looks good, feel free to merge when you are ready

**Pull request merged**
